[tool.poetry]
name = "ice-cream-dataops"
version = "0.1.0"
description = "bootcamp-21"
authors = ["Henrik Langesæter"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.10"
cognite-toolkit = "0.3.0b4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
